version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: rubocop
    versions:
    - "> 0.93.0"
  rebase-strategy: disabled
